version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: leetcode
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: leetcode
      MYSQL_DATABASE: leetcode
      MYSQL_USER: leetcode
      MYSQL_PASSWORD: leetcode
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local